[project]
name = "fabopsy-lib"
version = "0.1.0"
description = "Face and body based psychology analysis"
requires-python = ">=3.10"
dependencies = [
    "packaging>=25.0",
    "platformdirs>=4.5.1",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.3",
    "tomli>=2.3.0",
    "tqdm>=4.67.2",
]

[tool.setuptools.package-data]
fabopsy_lib = [
    "modules/*.json",
    "modules/*.toml",
    "modules/*.yaml",
    "modules/*.yml"
]

[dependency-groups]
dev = [
    "opencv-python>=4.13.0.90",
    "streamlit>=1.53.0",
]
