version = "1.0"

[module]
name = "Example Module"
version = "0.0.1"
description = "This is an example module"
keywords = ["Example", "Module"]
requirements = ['cowsay']

[[packages]]
name = "Example Package"
version = "0.0.1"
description = "This is an example package. Use to build pipeline to run."
keywords = ["Example", "Package"]

usage_models = []
inputs = []
provides = ["example/output"]
requires = []

[packages.entry]
method = "fabopsy_lib.example.example.load_package"

[[packages.parameters]]
name = "min_face"
type = "integer"
value = 80
description = 'Min face to detect'

[[packages.parameters]]
name = "threshold"
type = "number"
value = 0.8
description = 'Threshold of face'

[[packages.parameters]]
name = "object_name"
type = "string"
value = "face"
description = 'Detection target name'

[[packages.parameters]]
name = "scale"
type = "selection"
value = "big"
selection = ["big", "small"]
description = 'Large?'

[[packages.parameters]]
name = "integer[]"
type = "integer[]"
value = [80]
description = 'Select multi integer'

[[packages.parameters]]
name = "number[]"
type = "number[]"
value = [0.8]
description = 'Select multi number'

[[packages.parameters]]
name = "string[]"
type = "string[]"
value = ["face"]
description = 'Select multi string'

[[packages.parameters]]
name = "selection[]"
type = "selection[]"
value = ["big"]
selection = ["big", "small"]
description = 'Select multi selection'

[[packages.parameters]]
name = "object"
type = "object"
value = '{}'
description = 'Edit object'

[[packages.models]]
name = "Example Model"
version = "0.0.1"
description = "This is an example model. Unable to download and cannot be persistent cached."
keywords = ["Example", "Model"]
usage = ""
recommended = true

[packages.models.entry]
method = "fabopsy_lib.example.example.load_model"
